# Generated by Django 4.2.7 on 2023-11-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='회사명')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('date', models.DateTimeField(verbose_name='작성일')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('url', models.URLField(verbose_name='링크')),
                ('comapny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.company', verbose_name='회사')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200, verbose_name='태그 내용')),
            ],
        ),
        migrations.CreateModel(
            name='Post_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.post', verbose_name='게시글')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.tag', verbose_name='태그')),
            ],
        ),
        migrations.CreateModel(
            name='Comapny_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updates', models.DateTimeField(verbose_name='업데이트 날짜')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.company', verbose_name='회사')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.tag', verbose_name='태그 내용')),
            ],
        ),
    ]
