# Generated by Django 4.2.7 on 2023-11-07 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comapny',
            new_name='company',
        ),
    ]
