# Generated by Django 4.2.7 on 2023-11-07 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0002_rename_comapny_post_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comapny_Tag',
            new_name='Company_Tag',
        ),
    ]
